- hosts: localhost
  connection: local
  gather_facts: false
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - vars/vars_config.yml
  tasks:
    - include: tasks/Preparation.yml

    - include: tasks/get_tag_list.yml select_sign="1"
      with_items: "{{base_image_list}}"
      loop_control:
        loop_var: outer_item
      when: 
        - base_image_list is defined
        - base_image_list != []

    - include: tasks/get_tag_list.yml select_sign="0"
      with_items: "{{openshift_image_list}}"
      loop_control:
        loop_var: outer_item
      when: 
        - openshift_image_list is defined
        - openshift_image_list != []

    - include: tasks/get_tag_list.yml select_sign="0"
      with_items: "{{rhscl_image_list}}"
      loop_control:
        loop_var: outer_item
      when: 
        - rhscl_image_list is defined
        - rhscl_image_list != []

    - include: tasks/get_tag_list.yml select_sign="0"
      with_items: "{{jboss_image_list}}"
      loop_control:
        loop_var: outer_item
      when: 
        - jboss_image_list is defined
        - jboss_image_list != []

    - include: tasks/get_tag_list.yml select_sign="0"
      with_items: "{{other_image_list}}"
      loop_control:
        loop_var: outer_item
      when: 
        - other_image_list is defined
        - other_image_list != []
