- name: set fact image_name
  set_fact:
    image_name: "{{outer_item}}"
    sign: "{{select_sign}}"

- name: get tag list
  uri:
    url: "{{public_registry_url}}/{{image_name}}/tags/list"
    return_content: yes
    Content-type: "application/json"
    body_format: json
    status_code: 200
  register: tag_list
  ignore_errors: True

- name: set fact tag content
  set_fact:
    tag_content: "{{tag_list.content}}"

- name: set fact tag list
  set_fact:
    image_tag_list: "{{tag_content.tags|sort}}"
    imagefile_path: /tmp/imagelist/{{image_name}}

- name: create dir of imagelist file
  file: path={{imagefile_path}} state=directory

- name: save image list in tempfile
  template: src=../templates/image_list.j2 dest={{imagefile_path}}/image_list
  when: save_imagelist == "true"

- name: get time
  command: "/bin/date +%Y-%m-%d_%H:%M:%S"
  register: DATE_CMD

- set_fact:
    startDate: "{{DATE_CMD.stdout}}"

- include: base_image.yml
  when: sign == "1"

- include: openshift_image.yml
  when: sign != "1"
