- name: set fact image_name
  set_fact:
    image_name: "{{outer_item}}"
    sign: "{{select_sign}}"

- block:
   - name: get openshift image tag list
     uri:
       url: "{{public_registry_url}}/{{image_name}}/tags/list"
       return_content: yes
       Content-type: "application/json"
       body_format: json
       status_code: 200
     register: tag_list_1
     ignore_errors: True
   - name: set fact tag content
     set_fact:
       tag_content: "{{tag_list_1.content}}"
  when: sign != "2"

- block:
   - name: get tag list
     uri:
       url: "{{public_registry_url_2}}/{{image_name}}/tags/list"
       return_content: yes
       Content-type: "application/json"
       body_format: json
       status_code: 200
     register: tag_list_2
     ignore_errors: True
   - name: set fact tag content
     set_fact:
       tag_content: "{{tag_list_2.content}}"
  when: sign == "2"

- name: set fact tag list
  set_fact:
    image_tag_list: "{{tag_content.tags|sort}}"
    imagefile_path: /tmp/imagelist/{{image_name}}

- name: create dir of imagelist file
  file: path={{imagefile_path}} state=directory

- name: save image list in tempfile
  template: src=../templates/image_list.j2 dest={{imagefile_path}}/image_list
  when: save_imagelist == "true"

- include: base_image.yml
  when: sign == "1"

- include: openshift_image.yml
  when: sign != "1"
