- fail: msg="when use_network,please set registry_name"
  when:
    - use_network == "true"
    - local_registry is undefined

- fail: msg="image list is empty"
  when:
    - base_image_list == []
    - openshift_image_list == []
    - rhscl_image_list == []
    - jboss_image_list == []
    - other_image_list == []

- name: get time
  command: "/bin/date +%Y-%m-%d_%H:%M:%S"
  register: DATE_CMD

- set_fact:
    startDate: "{{DATE_CMD.stdout}}"
