- name: set fact base_image
  set_fact:
    base_image: "{{outer_item}}"

- name: get tag list
  uri:
    url: "{{public_registry_url}}/{{base_image}}/tags/list"
    return_content: yes
    Content-type: "application/json"
    body_format: json
    status_code: 200
  register: tag_list

- name: set fact tag content
  set_fact:
    tag_content: "{{tag_list.content}}"

- name: set fact tag list
  set_fact:
    image_tag_list: "{{tag_content.tags|sort}}"

- block:
    - name: create dir of imagelist file
      file: path=/tmp/imagelist/{{base_image}} state=directory
    - name: save image list in tempfile
      template: src=templates/image_list.j2 dest=/tmp/imagelist/{{base_image}}/image_list
  when: save_imagelist == "true"

- name: set fact image name
  set_fact: 
    image_name: "{{base_image}}"

- include: pull_image.yml  image_tag="{{item}}"
  with_items: "{{image_tag_list}}"
  when: item > "{{version}}"
