#image list you want sync.
#use '#' note beginning of image line can disable sync of image.
#when list is null,please add [] end of imagelist name.example base_image_list: []
base_image_list: []
  #- openshift3/ose-haproxy-router
  #- openshift3/ose-docker-builder
  #- openshift3/ose-sti-builder
  #- openshift3/ose-deployer
  #- openshift3/ose-docker-registry
  #- openshift3/ose-keepalived-ipfailover
  #- openshift3/ose-pod

openshift_image_list:
  #- openshift3/mongodb-24-rhel7
  #- openshift3/mysql-55-rhel7
  #- openshift3/postgresql-92-rhel7
  #- openshift3/nodejs-010-rhel7
  #- openshift3/php-55-rhel7
  #- openshift3/ruby-20-rhel7
  #- openshift3/python-33-rhel7
  #- openshift3/perl-516-rhel7
  #- openshift3/jenkins-1-rhel7
  #- openshift3/jenkins-slave-maven-rhel7
  #- openshift3/jenkins-slave-nodejs-rhel7
  #- openshift3/jenkins-slave-base-rhel7
  #- openshift3/openvswitch
  - openshift3/node
  - openshift3/ose
  - openshift3/ose-egress-router
  - openshift3/ose-f5-router
  - openshift3/ose-recycler
  - openshift3/registry-console
  - openshift3/metrics-hawkular-metrics
  - openshift3/metrics-heapster
  - openshift3/metrics-deployer
  - openshift3/metrics-cassandra
  - openshift3/logging-auth-proxy
  - openshift3/logging-elasticsearch
  - openshift3/logging-curator
  - openshift3/logging-kibana
  - openshift3/logging-fluentd
  - openshift3/logging-deployer
  - openshift3/logging-deployment
  - openshift3/image-inspector
  
rhscl_image_list:
  - rhscl/mariadb-101-rhel7
  - rhscl/mongodb-32-rhel7
  - rhscl/mongodb-26-rhel7
  - rhscl/mysql-56-rhel7
  - rhscl/nodejs-4-rhel7
  - rhscl/php-56-rhel7
  - rhscl/postgresql-94-rhel7
  - rhscl/postgresql-95-rhel7
  - rhscl/python-35-rhel7
  - rhscl/python-34-rhel7
  - rhscl/python-27-rhel7
  - rhscl/ruby-23-rhel7
  - rhscl/ruby-22-rhel7
  - rhscl/s2i-base-rhel7
  - rhscl/perl-520-rhel7
  - rhscl/nginx-18-rhel7
  - rhscl/nginx-16-rhel7
  - rhscl/httpd-24-rhel7
  
jboss_image_list:
  - jboss-fuse-6/fis-java-openshift
  - jboss-fuse-6/fis-karaf-openshift
  - jboss-amq-6/amq62-openshift
  - jboss-decisionserver-6/decisionserver62-openshift
  - jboss-eap-6/eap64-openshift
  - jboss-decisionserver-6/decisionserver63-openshift
  - jboss-eap-6/eap64-openshift
  - jboss-eap-7/eap70-openshift
  - jboss-webserver-3/webserver30-tomcat7-openshift
  - jboss-webserver-3/webserver30-tomcat8-openshift
  - jboss-datagrid-6/datagrid65-openshift
  - jboss-processserver-6/processserver63-openshift
  
other_image_list:
  - rhel7/etcd
  - rhel7/pod-infrastructure
  - cloudforms/cfme4
  - rhel7.2
  - rhel7.3
  - redhat-sso-7/sso70-openshift
  - dotnet/dotnetcore-10-rhel7

#public regsitry API URL
public_registry_url: https://access.redhat.com/webassets/docker/content/dist/rhel/server/7/7Server/x86_64/ose/3/containers/registry

#image version greater than this will pull,only take effect in base_image_list. tag :latest not download.
version: v3.3

#whether or not save all image tag list,must "true" or "false"
save_imagelist: "true"

#chose which type to push image,network or tar. default network.fasle will use tar,but is not Support now.nust "true" or "false"
use_network: "true"

#local registry which you will push image to.
local_registry: registry.example.com:5000

#public registry which you will pull image from.
public_registry: registry.access.redhat.com
